### ISSUE TITLE
Search Not Working 

### ISSUE THREAD

**Issue by atif92** [tadijam64/search-engines-comparison#48]
I cloned this project and build and deployed the Package to my Running instance of AEM 6.5 with Java 8. I also executed both groovy scripts, I can see the search component showing all three options of Lucene, Solr and Elastic but none of them is doing any search when I type anything eg "Shirt". Is there any other configuration we have to do if we have cloned the whole repo?

**Comment by tadijam64** [comment]
Hi @atif92 ,

thank you for your interest in this project.
I will get back to you as soon as I check what could cause your issue.

Can you give me details regarding your AEM, Apache Solr and Elasticsearch versions?

Best Regards,

**Comment by atif92** [comment]
@tadijam64 I am running local instance of AEM 6.5 Jar and Elastic 7.6.2 both on my local windows machine, however I did not installed Solr as I was more interested in Elastic.

**Comment by tadijam64** [comment]
@atif92 Looks like Jackson dependency bothered it. Can you please re-check now?

**Comment by atif92** [comment]
Thanks for fixing this for AEM 6.5. works like charm now.
